export const authConstants = {
    GET_CURRENT_USER_SIGN_IN: "GET_CURRENT_USER_SIGN_IN",

    USER_SIGN_OUT_LOADING: "USER_SIGN_OUT_LOADING",
    USER_SIGN_OUT_SUCCESSFUL: "USER_SIGN_OUT_SUCCESSFUL",
    USER_SIGN_OUT_FAILURE: "USER_SIGN_OUT_FAILURE",

    USER_GOOGLE_SIGN_IN_LOADING: "USER_GOOGLE_SIGN_IN_LOADING",
    USER_GOOGLE_SIGN_IN_SUCCESS: "USER_GOOGLE_SIGN_IN_SUCCESS",
    USER_GOOGLE_SIGN_IN_FAILURE: "USER_GOOGLE_SIGN_IN_FAILURE",
};

export const videoConstants = {
    GET_ALL_VIDEOS_LOADING: "GET_ALL_VIDEOS_LOADING",
    GET_ALL_VIDEOS_SUCCESS: "GET_ALL_VIDEOS_SUCCESS",
    GET_ALL_VIDEOS_FAILURE: "GET_ALL_VIDEOS_FAILURE",

    GET_VIDEO_CONTENTS_LOADING: 'GET_VIDEO_CONTENTS_LOADING',
    GET_VIDEO_CONTENT_SUCCESS: 'GET_VIDEO_CONTENTS_SUCCESS',
    GET_VIDEO_CONTENT_FAILURE: 'GET_VIDEO_CONTENT_FAILURE',

    UPLOAD_VIDEO_AND_CONTENT_LOADING: 'UPLOAD_VIDEO_AND_CONTENT_LOADING',
    UPLOAD_VIDEO_AND_CONTENT_SUCCESS: 'UPLOAD_VIDEO_AND_CONTENT_SUCCESS',
    UPLOAD_VIDEO_AND_CONTENT_FAILURE: 'UPLOAD_VIDEO_AND_CONTENT_FAILURE',
};
