export const authConstants = {
    GET_CURRENT_USER_SIGN_IN: "GET_CURRENT_USER_SIGN_IN",

    USER_SIGN_OUT_LOADING: "USER_SIGN_OUT_LOADING",
    USER_SIGN_OUT_SUCCESSFUL: "USER_SIGN_OUT_SUCCESSFUL",
    USER_SIGN_OUT_FAILURE: "USER_SIGN_OUT_FAILURE",

    USER_GOOGLE_SIGN_IN_LOADING: "USER_GOOGLE_SIGN_IN_LOADING",
    USER_GOOGLE_SIGN_IN_SUCCESS: "USER_GOOGLE_SIGN_IN_SUCCESS",
    USER_GOOGLE_SIGN_IN_FAILURE: "USER_GOOGLE_SIGN_IN_FAILURE",
};

export const videoConstants = {
    GET_ALL_VIDEOS_LOADING: "GET_ALL_VIDEOS_LOADING",
    GET_ALL_VIDEOS_SUCCESS: "GET_ALL_VIDEOS_SUCCESS",
    GET_ALL_VIDEOS_FAILURE: "GET_ALL_VIDEOS_FAILURE",

    GET_VIDEO_CONTENTS_LOADING: 'GET_VIDEO_CONTENTS_LOADING',
    GET_VIDEO_CONTENT_SUCCESS: 'GET_VIDEO_CONTENTS_SUCCESS',
    GET_VIDEO_CONTENT_FAILURE: 'GET_VIDEO_CONTENT_FAILURE',

    UPLOAD_VIDEO_AND_CONTENT_LOADING: 'UPLOAD_VIDEO_AND_CONTENT_LOADING',
    UPLOAD_VIDEO_AND_CONTENT_SUCCESS: 'UPLOAD_VIDEO_AND_CONTENT_SUCCESS',
    UPLOAD_VIDEO_AND_CONTENT_FAILURE: 'UPLOAD_VIDEO_AND_CONTENT_FAILURE',

    TASK_LOADING: 'TASK_LOADING',
    TASK_SUCCESS: 'TASK_SUCCESS',
    TASK_FAILURE: 'TASK_FAILURE',

    UPLOAD_QUIZ_LOADING: 'UPLOAD_QUIZ_LOADING',
    UPLOAD_QUIZ_SUCCESS: "UPLOAD_QUIZ_SUCCESS",
    UPLOAD_QUIZ_FAILURE: "UPLOAD_QUIZ_FAILURE",

    UPDATE_QUIZ_LOADING: 'UPDATE_QUIZ_LOADING',
    UPDATE_QUIZ_SUCCESS: 'UPDATE_QUIZ_SUCCESS',
    UPDATE_QUIZ_FAILURE: 'UPDATE_QUIZ_FAILURE',

    UPLOAD_INTERVIEW_SUCCESS: 'UPLOAD_INTERVIEW_SUCCESS',
    UPLOAD_INTERVIEW_LOADING: 'UPLOAD_INTERVIEW_LOADING',
    UPLOAD_INTERVIEW_FAILURE: 'UPLOAD_INTERVIEW_FAILURE',

    UPDATE_INTERVIEW_LOADING: 'UPDATE_INTERVIEW_LOADING',
    UPDATE_INTERVIEW_SUCCESS: 'UPDATE_INTERVIEW_SUCCESS',
    UPDATE_INTERVIEW_FAILURE: 'UPDATE_INTERVIEW_FAILURE',

    UPLOAD_FURTHER_READING_LOADING: 'UPLOAD_FURTHER_READING_LOADING',
    UPLOAD_FURTHER_READING_SUCCESS: 'UPLOAD_FURTHER_READING_SUCCESS',
    UPLOAD_FURTHER_READING_FAILURE: 'UPLOAD_FURTHER_READING_FAILURE',

    UPDATE_FURTHER_READING_LOADING: 'UPDATE_FURTHER_READING_LOADING',
    UPDATE_FURTHER_READING_SUCCESS: 'UPDATE_FURTHER_READING_SUCCESS',
    UPDATE_FURTHER_READING_FAILURE: 'UPDATE_FURTHER_READING_FAILURE',
};
